services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./:/workspace:Z
    env_file:
      - .env
    command: sleep infinity
    environment: # REMOVE IT'S OLD
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]